### ISSUE TITLE
[Extension] Store and keep wallet wallet state persistent

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#112]
**Is your feature request related to a problem? Please describe.**
Parent task: https://github.com/CasperDash/casperdash-client/issues/10

- [x] Store application state in a persistent storage. (Solution to be researched and applied)
- [x] Without Locking, User can see the last state where User last visited.
- [x] When Locked, User must enter password for authentication.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gaupoit** [comment]
hi @djhahe , please update the requirements if it's still missing st. a @duc-q please do the solution research first and confirm with me and @djhahe before implementation. Cheers.

**Comment by duc-q** [comment]
hi @gaupoit ,

Please review and merge new update when you finish.

Thanks
