### ISSUE TITLE
[Web App|Extension] Implement Marketing/Promotion Banner

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#114]
**Is your feature request related to a problem? Please describe.**
We need to show the promotion banner in our Wallet when running the marketing campaign.

Example:

![Screen Shot 2022-08-08 at 11 17 49](https://user-images.githubusercontent.com/4486806/183338160-70103106-bc57-41cb-aef4-4719206e459c.png)

**Describe the solution you'd like**
The client will fetch the promotion banner information via API `/configurations` with these properties:

|key|type|description|
|------|------|--------|
|campaign|string|Campaign name, eg: Everstake|
|content|html|Campaign headline, eg: Join, compete & win! Prize pool of <b>$100,000</b>|
|image|string|Campaign image link|
|cta|string|Call to Action's link|

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by djhahe** [comment]
Implemented with news section, closing this for now.
