### ISSUE TITLE
[Extension] It show $0.03 when user doesn't have any CSPR

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#115]
**Describe the bug**

![Screen Shot 2022-08-08 at 11 12 08](https://user-images.githubusercontent.com/4486806/183339331-79589baf-4152-49f8-8426-a77e6167c91b.png)

**To Reproduce**
1. Go to Home tab with zero balance
2. See the 0.03$ in CSPR row

**Expected behavior**
Should show 0

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Browser: Chrome

**Additional context**
N/A

**Comment by duc-q** [comment]
@gaupoit 

I did a quick investigation on this issue and found out this:

The final price `0.03` comes from `current_price`, based on this request from `https://api.coingecko.com/`

![image](https://user-images.githubusercontent.com/610234/183418634-f80d35c0-6d1a-4ac3-a82d-97b0623ecd67.png)

That means we're showing the current market price of CSPR, not how much value User is owning the coin in current wallet.

Please help to recheck with @djhahe ,

Thanks

**Comment by gaupoit** [comment]
> 

hi @duc-q , please follow this design.

![Screen Shot 2022-08-09 at 09 28 19](https://user-images.githubusercontent.com/4486806/183550264-68ee921b-6510-4824-ac9d-9049cd807e26.png)

**Comment by gaupoit** [comment]
> @gaupoit
> 
> I did a quick investigation on this issue and found out this:
> 
> The final price `0.03` comes from `current_price`, based on this request from `https://api.coingecko.com/`
> 
> ![image](https://user-images.githubusercontent.com/610234/183418634-f80d35c0-6d1a-4ac3-a82d-97b0623ecd67.png)
> 
> That means we're showing the current market price of CSPR, not how much value User is owning the coin in current wallet.
> 
> Please help to recheck with @djhahe ,
> 
> Thanks

We have balance case. 
![Screen Shot 2022-08-09 at 09 29 11](https://user-images.githubusercontent.com/4486806/183550382-802e13ff-cd82-4e14-bcc2-5282b44cde3b.png)
