### ISSUE TITLE
[Improvement] Please help to check if we need update permission in manifest.json to use chrome storage.

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#117]
@duc-q Please help to check if we need update permission in manifest.json to use chrome storage.
LGTM for now, in future we may need to consider to store state in memory as the article (https://auth0.com/blog/secure-browser-storage-the-facts/)

_Originally posted by @djhahe in https://github.com/CasperDash/casperdash-client/issues/113#issuecomment-1211011219_

**Comment by duc-q** [comment]
@gaupoit 

This ticket can be closed
