### ISSUE TITLE
[Improvement] Improve the Recovery Phase Feature

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#121]
**Is your feature request related to a problem? Please describe.**

Allow user to 

- [ ] Copy
- [ ] Download

the Recovery Phase

Rename the "Next" button to "I SAVED MY RECOVRY PHASE" => it's a reminder for users to save their recovery phase.

![Screen Shot 2022-08-14 at 11 49 21](https://user-images.githubusercontent.com/4486806/184522952-f777b383-9bd7-48c4-8571-adc6c9558a3d.png)

**Describe the solution you'd like**
We can add the "Copy" and "Download" button below the phase.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by djhahe** [comment]
https://github.com/CasperDash/casperdash-client/pull/141
