### ISSUE TITLE
[Account Management] Import recovery phase

### ISSUE THREAD

**Issue by djhahe** [CasperDash/casperdash-client#122]
**Is your feature request related to a problem? Please describe.**
Add screen to import recovery phase
![image](https://user-images.githubusercontent.com/6711653/184606773-51ea88ff-d0a7-441e-a2a5-0ea0a7e1e596.png)

**Comment by gaupoit** [comment]
hi @hoailinh1210 , please continue and complete this ticket.

**Comment by ducquach-groove** [comment]
hi @hoailinh1210 

Please use this branch, `https://github.com/CasperDash/casperdash-client/tree/feature/CD-122-extension-import-connect-account` , it was already created and in WIP status.

Thanks,

**Comment by duc-q** [comment]
hi @hoailinh1210

Please use this branch, https://github.com/CasperDash/casperdash-client/tree/feature/CD-122-extension-import-connect-account , it was already created and in WIP status.

Thanks,

**Comment by duc-q** [comment]
@djhahe  @gaupoit  @hoailinh1210 

A few notes before staring on the implementation, might need discussion:
- Most of the logic code from Import Wallet should be the same as Creating new wallet, including: Password creation, `useCreateUser` hook, and choosing Encryption type (coming soon from another ticket)
- From the Miro User flow, we probably should re-structure a bit to make these components re-usable.
- My suggestion is: 
  - Partially reuse `createWallet` reducer
  - Create common `CreatePasswordPage` in `web-extension/Common` folder
  - Each module (Create Wallet, Import Keyphrase) will have its own `CreatePasswordPage` component as container for specific logic. E.g:
    -  Create Wallet: reset custom header (move related logic into this component).
    -  Import Keyphrase: should import and render `CreatePasswordPage` normally, no further logic required.
  - The same mechanism applies for `RecoveryPhrasePage`, we can just render keyphrase, and move its logic into specific container for each module if necessary.

Let me know if there's any addition requirement or obstacles if following this approach,

**Comment by djhahe** [comment]
thanks @duc-q, sounds good to me.
@hoailinh1210 please check and follow up if you have any questions
