### ISSUE TITLE
[Extension] Need to ask user to enter password before signing the deploy

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#135]
**Is your feature request related to a problem? Please describe.**
To temporarily mitigate the user info issues with service worker, the extension needs to ask users to enter the password before signing deploy action. 

**Describe the solution you'd like**
Affected features:

- Send CSPR
- Staking 

Suggestion: ~~handle logic in `useSigner`~~ , @djhahe please advise more about this.

**Describe alternatives you've considered**
In term of UI, we can reuse this screen and replacing by Password form.

![Screen Shot 2022-09-06 at 15 06 33](https://user-images.githubusercontent.com/4486806/188581160-d7d844ab-bfa9-4f7b-9c22-6f3a7e4195f4.png)

**Additional context**
Related ticket: #111

**Comment by djhahe** [comment]
Sw is working well and stable not, this one could be close without changes
