### ISSUE TITLE
[Extension] Do not need display "Required." validation message in Transfer ID field

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#138]
**Describe the bug**

![Screen Shot 2022-09-06 at 16 29 34](https://user-images.githubusercontent.com/4486806/188600010-c9b7bf25-4a18-4201-a1d7-06b24fc70fca.png)

**To Reproduce**
1. Go to 'Send CSPR' form
2. Enter the CSPR amount is bigger than wallet balance
3. Should see the "Required" error in Transfer ID field

**Expected behavior**
Should not display the "Required" error in Transfer ID field

**Comment by djhahe** [comment]
Fixed
