### ISSUE TITLE
[Mobile/iOS] Hide wallet content when User is switching between applications

### ISSUE THREAD

**Issue by duc-q** [CasperDash/casperdash-client#142]
**Is your feature request related to a problem? Please describe.**
As an iOS user, I notice one common feature from other wallet app, or e-banking application, that they would hide the app screen content while user is switching between apps.

**Describe the solution you'd like**
We can simply show the Casper icon when User is in this mode.
![image](https://user-images.githubusercontent.com/610234/189839615-21b50442-b0ee-4ef2-8486-26f50431911a.png)

![image](https://user-images.githubusercontent.com/610234/189839556-bc5d906b-d18f-4fc4-baad-2b83b7c0012a.png)

**Comment by djhahe** [comment]
thanks for suggestion @duc-q , please help to move this to Mobile repo
