### ISSUE TITLE
[Browser Extension] View staking rewards 

### ISSUE THREAD

**Issue by djhahe** [CasperDash/casperdash-client#184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gaupoit** [comment]
All done

![Screenshot 2023-07-31 at 09 12 40](https://github.com/CasperDash/casperdash-client/assets/4486806/83da0b4a-e0c3-4c9d-a1d7-9e4d4ed49675)
