### ISSUE TITLE
[UI/UX Improvement] There are some UI improvements we need to improve in next release

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#189]
**Is your feature request related to a problem? Please describe.**
1. Sync text and UX behavior with mobile
![ux-1](https://user-images.githubusercontent.com/4486806/203318715-59a0baa4-27f1-4a5f-8652-eb0baf9a3cb2.png)

**Comment by gaupoit** [comment]
hi @hoailinh1210 , could you help to fix it?

**Comment by djhahe** [comment]
Fixed
