### ISSUE TITLE
[Performance Issue] High CPU Usage when using CD Extension

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#194]
**Describe the bug**
<img width="1275" alt="high-cpu-cd" src="https://user-images.githubusercontent.com/4486806/208014607-d4091734-f329-4b40-8f3b-bb7863b33ca4.png">

**Comment by gaupoit** [comment]
Problem solved.

**Comment by gaupoit** [comment]
hi @djhahe , please help to link the related commit / PR

**Comment by djhahe** [comment]
update keep sw alive in v.1.5.0
