### ISSUE TITLE
[Question] User can import account with public key

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#203]
**Describe the bug**
Is it a bug or feature @djhahe @hoailinh1210 ?

**Comment by gaupoit** [comment]
![Screenshot 2023-01-06 at 07 44 02](https://user-images.githubusercontent.com/4486806/210906807-837db52d-3bf4-423e-a103-4f779f5afe93.png)
![Screenshot 2023-01-06 at 07 44 32](https://user-images.githubusercontent.com/4486806/210906870-6d6dff73-6d88-4f3a-a194-028acd59e0ee.png)

**Comment by djhahe** [comment]
Cant reproducible
