### ISSUE TITLE
[Extension] Link account to block explorer

### ISSUE THREAD

**Issue by djhahe** [CasperDash/casperdash-client#220]
**Is your feature request related to a problem? Please describe.**
As User I want to see my account in block explorer

**Describe the solution you'd like**
Add a button to open the account in block explorer

**Describe alternatives you've considered**

**Additional context**

**Comment by gaupoit** [comment]
Proof:

![Screenshot 2023-07-24 at 16 03 40](https://github.com/CasperDash/casperdash-client/assets/4486806/7be41fc7-6a77-4fdb-9953-1bb57fc0c6c0)
