### ISSUE TITLE
[Improvement] Allow users to download private key without viewing them

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#230]
**Is your feature request related to a problem? Please describe.**

As the users, I would like to download directly my private key without viewing it.
![Screenshot 2023-03-27 at 10 52 17](https://user-images.githubusercontent.com/4486806/227836729-a4ff3ae7-e2bb-43fa-aa31-569d875f8e6a.png)

**Comment by djhahe** [comment]
we will not allow user to download private key
