### ISSUE TITLE
[Recovery Phase] Import Recovery Phase from Casper Wallet

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#245]
**Is your feature request related to a problem? Please describe.**
As the user, I would like to import recovery phase from Casper Wallet to CasperDash Wallet.

**Describe the solution you'd like**
Currently, user can import. However the public key is different.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gaupoit** [comment]
hi @djhahe @codsay , please have a look and give us the root cause. We need to explain for users. Thanks.

**Comment by codsay** [comment]
> hi @djhahe @codsay , please have a look and give us the root cause. We need to explain for users. Thanks.
to support different wallet path
