### ISSUE TITLE
Dapp Signing page - show the contract hash the deploy is interacting with

### ISSUE THREAD

**Issue by djhahe** [CasperDash/casperdash-client#270]
**Is your feature request related to a problem? Please describe.**
we should show the contract hash when user's signing deploy, also it should be clickable to view the contract in explorer
<img width="681" alt="image" src="https://github.com/CasperDash/casperdash-client/assets/6711653/8a9f30f0-ade0-46e7-b74f-dce78d600f41">

**Comment by gaupoit** [comment]
![Screenshot 2023-08-28 at 14 21 49](https://github.com/CasperDash/casperdash-client/assets/4486806/5d9550c8-967b-4905-8857-500504e666f6)

**Comment by gaupoit** [comment]
![Screenshot 2023-08-28 at 14 22 09](https://github.com/CasperDash/casperdash-client/assets/4486806/2539c30e-2a89-45d2-819b-1c677939a47e)
