### ISSUE TITLE
[Forgot Password] Show Forgot Password option in Lock Screen

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#304]
**Is your feature request related to a problem? Please describe.**
There are few users contact CM because they forgot their passwords. And they do not know how to do next steps. It's helpful to add the forgot password link / button to guide them.

**Describe the solution you'd like**
![forgot-password](https://github.com/CasperDash/casperdash-client/assets/4486806/e5c43be2-e56b-408a-8afa-62fc82398fcc)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gaupoit** [comment]
hi @hoailinh1210 @djhahe , I think the text should be "Forgot Password?" 
![Screenshot 2023-08-28 at 14 24 11](https://github.com/CasperDash/casperdash-client/assets/4486806/082cfd8b-ab1c-4376-aba9-fa6614bbf268)

**Comment by gaupoit** [comment]
![Screenshot 2023-08-28 at 14 27 11](https://github.com/CasperDash/casperdash-client/assets/4486806/f650e3b9-a50e-41cb-98ae-d2d7398990cd)
![Screenshot 2023-08-28 at 14 29 41](https://github.com/CasperDash/casperdash-client/assets/4486806/c37a8cb7-9fba-4d7b-87e0-c7e1063cd83c)

My suggestion for the typo. Thanks.

**Comment by gaupoit** [comment]
![Screenshot 2023-08-28 at 14 31 03](https://github.com/CasperDash/casperdash-client/assets/4486806/3897adfb-7710-46d2-86e5-c0ed1c162cc8)

UI Bug - Cannot see the text box.

**Comment by hoailinh1210** [comment]
Hi @gaupoit , I fixed on PR #335 and merged on release/1.6.0, please take a look on it
