### ISSUE TITLE
[Ledger] Research ledger connection lib

### ISSUE THREAD

**Issue by djhahe** [CasperDash/casperdash-client#53]
**Is your feature request related to a problem? Please describe.**
- Research ledger connection lib and provide solution to integrate with casperdash.io

- [x] Install casper app on Ledger
Notes: need to enable development mode
- [x] Write the demo to connect with Ledger
Lib: https://github.com/LedgerHQ/ledgerjs
https://www.npmjs.com/package/@zondax/ledger-casper

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gaupoit** [comment]
Status update: 

- Can get public key when connect to Ledger
- Can sign transfer deploy
