### ISSUE TITLE
[NFT] Transfer NFT

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#89]
**Is your feature request related to a problem? Please describe.**
As the NFT author, I want to transfer my NFT to other user.

**Describe the solution you'd like**
- Call transfer endpoint 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AirNavyFan** [comment]
Cool. Thx for showing a better way.

**Comment by AirNavyFan** [comment]
What is this that Lego NFT. Send cease and desist until you formalize. Apple wallet what's that about? Airport hangar who's using my resources and pilots?

**Comment by AirNavyFan** [comment]
Where's dev ops and Microsoft teams/films etc. What media company are we working with? Has anyone called China or HK figured out what's up with P new media? What's up with omnicom and Xander att. Stop your fake sex stings too and delete any links or attachment to my name.

Thx

**Comment by AirNavyFan** [comment]
Who has access to all gmails, yahoos, outlooks, Thales etc. Delete all access and revoke reassign.

**Comment by AirNavyFan** [comment]
Can someone reach out to the US attorneys and foreign consulates today? Thx.
