### ISSUE TITLE
[Mint NFT] Mint NFT Page is Blank

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-client#93]
**Describe the bug**
As a user, I see the blank page when access the /createNFT link.

**To Reproduce**
1. Go to NFTs tab
2. Click on Mint NFT
3. See blank page

![Screen Shot 2022-04-21 at 16 18 24](https://user-images.githubusercontent.com/4486806/164422916-917b9d0d-6cb2-41d0-be9e-62cf9226015a.png)

**Expected behavior**
![Screen Shot 2022-04-21 at 16 18 36](https://user-images.githubusercontent.com/4486806/164422967-09616719-afca-4925-9623-8aa7737b0c20.png)

**Comment by djhahe** [comment]
I'm going to remove this feature on wallet, moving it to marketplace
