### ISSUE TITLE
[{Screen/Feature}] {Description}

### ISSUE THREAD

**Issue by sebastianstrzalkowski** [CasperDash/casperdash-client#99]
**Describe the bug**
Site reloading and failing after some time.

**To Reproduce**
1. Create NFT with 404 error on external_url (URL should be empty, bad like that: http://localhost:36773/assets/images/e9b8c91f5b6a270483e3.png)
2. Add contract to casper dash wallet.
3. See blank page

**Expected behavior**
Show empty NFT image
**Screenshots**
![image](https://user-images.githubusercontent.com/33623243/170698663-6ef676e2-c97b-4d0a-8394-5c18eabf2c6e.png)

**Smartphone (please complete the following information):**
-Chrome

**Comment by gaupoit** [comment]
I will close this task because we already have the new CasperDash Web APp.
